In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.pyplot import *
import gmaps
import gmaps.datasets
from geopy.geocoders import Nominatim

In [2]:
gmaps.configure(api_key="AIzaSyAfSZCrFOIKXV-i227K8HeEgPrcGXvXlzU") # Google API key

In [3]:
df_2016_1 = pd.read_csv('data/green_tripdata_2016-01.csv', parse_dates = ["lpep_pickup_datetime"],index_col="lpep_pickup_datetime")

In [4]:
df_2016_1.head()

,VendorID,Lpep_dropoff_datetime,Store_and_fwd_flag,RateCodeID,Pickup_longitude,Pickup_latitude,Dropoff_longitude,Dropoff_latitude,Passenger_count,Trip_distance,Fare_amount,Extra,MTA_tax,Tip_amount,Tolls_amount,Ehail_fee,improvement_surcharge,Total_amount,Payment_type,Trip_type
lpep_pickup_datetime,,,,,,,,,,,,,,,,,,,,
2016-01-01 00:29:24,2,2016-01-01 00:39:36,N,1,-73.928642,40.680611,-73.924278,40.698044,1,1.46,8.0,0.5,0.5,1.86,0.0,NaN,0.3,11.16,1,1.0
2016-01-01 00:19:39,2,2016-01-01 00:39:18,N,1,-73.952675,40.723175,-73.923920,40.761379,1,3.56,15.5,0.5,0.5,0.00,0.0,NaN,0.3,16.80,2,1.0
2016-01-01 00:19:33,2,2016-01-01 00:39:48,N,1,-73.971611,40.676105,-74.013161,40.646072,1,3.79,16.5,0.5,0.5,4.45,0.0,NaN,0.3,22.25,1,1.0
2016-01-01 00:22:12,2,2016-01-01 00:38:32,N,1,-73.989502,40.669579,-74.000648,40.689034,1,3.01,13.5,0.5,0.5,0.00,0.0,NaN,0.3,14.80,2,1.0
2016-01-01 00:24:01,2,2016-01-01 00:39:22,N,1,-73.964729,40.682854,-73.940720,40.663013,1,2.55,12.0,0.5,0.5,0.00,0.0,NaN,0.3,13.30,2,1.0

# Heat Map

In [5]:
def heatMap(dataFrame):
    figList = []
    for i in range(24):
        if i < 10:
            df = dataFrame['2016-01-01 0' + str(i)]
        else:
            df = dataFrame['2016-01-01 ' + str(i)]
        geo = geoInfo(df.Pickup_latitude,df.Pickup_longitude)[:500]
        fig = gmaps.figure()
        fig.add_layer(gmaps.heatmap_layer(geo))
        figList.append(fig)
    return figList

In [6]:
def geoInfo(latitude,longitude):
    p_lati = []
    p_long = []
    for pl in latitude:
        p_lati.append(pl)
    for pl in longitude:
        p_long.append(pl)
    return zip(p_lati,p_long)

In [8]:
heatMap(df_2016_1)[0]

Figure(layout=FigureLayout(height=u'420px'))